### ISSUE TITLE
What is a prototype..

### ISSUE THREAD

**Issue by joostf** [aaraar/web-app-from-scratch-1920#3]
https://github.com/aaraar/web-app-from-scratch-1920/blob/61b7b617429ccc9e13433dd62562d0f6ffb664a8/docs/js/app.js#L176

.. and why use it, instead of declaring functions directly in the constructor?

**Comment by aaraar** [comment]
It creates a Home prototype, just like an Array has a prototype.
The prototype then contains al the properties that you give it so that when you create a new Home object, all the properties are also usable in the new object.

The class syntax in JS is actually syntactic sugar over prototypes, they work the same internally

**Comment by joostf** [comment]
Sure, but if you create the functions (method) in the constructor, they are available in all instances aswqell.. what's the difference?

**Comment by aaraar** [comment]
Hmm, had me thinking on this one. 
My guess would be that if you define it in the prototype it would only be saved once, on the prototype, and not on every instance. You wouldn't need to declare/save every single function on every instance since the content would not change. Only the variables that change per instance (e.g. the name and the ID) would need to be created in the constructor.
